name: Continuous Integration and Delivery

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/pavlapintaric235/url-summary-api

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" |
          docker login ghcr.io \
            --username "${{ github.actor }}" \
            --password-stdin

      - name: Pull image
        run: |
          docker pull "${{ env.IMAGE }}:latest" || true

      - name: Build image
        run: |
          docker build \
            --cache-from "${{ env.IMAGE }}:latest" \
            --tag "${{ env.IMAGE }}:latest" \
            --file ./project/Dockerfile.prod \
            ./project

      - name: Push image
        run: |
          docker push "${{ env.IMAGE }}:latest"

  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" |
          docker login ghcr.io \
            --username "${{ github.actor }}" \
            --password-stdin

      - name: Pull image
        run: |
          docker pull "${{ env.IMAGE }}:latest"

      - name: Run container
        run: |
          docker run \
            --detach \
            --name fastapi-tdd \
            --env PORT=8765 \
            --env ENVIRONMENT=dev \
            --env DATABASE_URL=sqlite://sqlite.db \
            --env DATABASE_TEST_URL=sqlite://sqlite.db \
            --publish 5003:8765 \
            "${{ env.IMAGE }}:latest"

      - name: Pytest
        run: docker exec fastapi-tdd python -m pytest .

      - name: Flake8
        run: docker exec fastapi-tdd python -m flake8 .

      - name: Black
        run: docker exec fastapi-tdd python -m black . --check

      - name: isort
        run: docker exec fastapi-tdd python -m isort . --check-only